services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: addonis,keycloakdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./bash_script:/docker-entrypoint-initdb.d

  keycloak:
    image: jboss/keycloak
    depends_on:
      - postgres
    ports:
      - 8081:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_DATABASE: keycloakdb
      DB_USER: root
      DB_PASSWORD: root

      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /realm/keycloak-realm-settings.json
      KEYCLOAK_MIGRATION_ACTION: IMPORT
    volumes:
      - ./keycloak-realm-settings.json:/realm/keycloak-realm-settings.json